<?php
/**
 * Created by PhpStorm.
 * User: RaoHonghua
 * Date: 2017/6/7
 * Time: 16:46
 * e-mail: 706805346@qq.com
 * QQ/Wechat: 706805346/hua706805346
 */

namespace Admin\Model;


use Common\Model\BaseModel;

class BrandModel extends BaseModel
{
    // 主键名称
    protected $pk = 'b_id';
    // 数据表名（不包含表前缀）
    protected $tableName = 'brand';
    // 自动验证定义
    protected $_validate = [
        ['b_name','require','分类名称不能为空'],
    ];

    public function store($data)
    {
        return parent::store($data); // TODO: Change the autogenerated stub
    }
}