<?php
/**
 * Created by PhpStorm.
 * User: RaoHonghua
 * Date: 2017/6/6
 * Time: 10:57
 * e-mail: 706805346@qq.com
 * QQ/Wechat: 706805346/hua706805346
 */

namespace Admin\Model;


use Common\Model\BaseModel;

class TypeModel extends BaseModel
{
    // 主键名称
    protected $pk = 't_id';
    // 数据表名（不包含表前缀）
    protected $tableName = 'type';
    // 自动验证定义
    protected $_validate = [
        ['t_name','require','类型名称不能为空'],
    ];

    public function store($data)
    {
        return parent::store($data); // TODO: Change the autogenerated stub
    }
}