<?php
/**
 * Created by PhpStorm.
 * User: RaoHonghua
 * Date: 2017/6/6
 * Time: 16:09
 * e-mail: 706805346@qq.com
 * QQ/Wechat: 706805346/hua706805346
 */

namespace Admin\Model;


use Common\Model\BaseModel;

class TypeAttrModel extends BaseModel
{
    // 主键名称
    protected $pk = 't_id';
    // 数据表名
    protected $tableName = 'type_attr';
    // 自动验证定义
    protected $_validate = [
        ['attr_name','require','属性名称不能为空'],
        ['attr_value','require','属性值不能为空'],
    ];

    public function store($data)
    {
        return parent::store($data); // TODO: Change the autogenerated stub
    }

    /**
     * 编辑方法
     */
    public function edit ($data) {
        $typeAttr = M('type_attr');
        $editData['attr_name'] = $data['attr_name'];
        $editData['attr_value'] = $data['attr_value'];
        $editData['attr_type'] = $data['attr_type'];
        $editData['jn_type_t_id'] = $data['jn_type_t_id'];
        $typeAttr->where("ta_id='{$data['ta_id']}'")->save($editData);
        return ['valid'=>'success','msg'=>'编辑成功'];
    }

    /**
     * 添加方法
     */
    public function adds ($data) {
        $typeAttr = M('type_attr');
        $addData['attr_name'] = $data['attr_name'];
        $addData['attr_value'] = $data['attr_value'];
        $addData['attr_type'] = $data['attr_type'];
        $addData['jn_type_t_id'] = $data['jn_type_t_id'];
        $typeAttr->data($addData)->add();
        return ['valid'=>'success','msg'=>'添加成功'];
    }
}